runtime: python39

entrypoint: gunicorn -b :$PORT  mahdi.wsgi

env_variables:
  SECRET_KEY: 'django-insecure-yhq+j&mdd25u9-jv$5d^0@bd-4271v&2w93iqc9f46_v&n-$ri'
  DEBUG: 'False'
  DB_NAME: 'uclab37'
  DB_USER: 'demo123'
  DB_PASSWORD: '2l95zbF|{G?gaf|a'
  DB_HOST: 'mahdiweb-9af5f:us-central1:uclab37'

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: 'mahdiweb-9af5f:us-central1:uclab37'

runtime_config:
  python_version: 3.9
  requirements_update_strategy: "update"